env:
  global:
    - SNYK_TOKEN=4d950846-8786-402e-845d-2fc86442fba9
    - PAGES_USER=html-pages
    - PAGES_PASSWORD=1904

os:
  - linux
  - osx

sudo: false

dist: trusty

language: node_js

node_js:
  - "8"
  - "9"
  - "10"
  - "11"

notifications:
  email:
    on_success: never # default: change
    on_failure: always # default: always
