# version format
# you can use {branch} name in version format too
version: 1.0.{build}

# environment variables
environment:
  global:
    SNYK_TOKEN: 4d950846-8786-402e-845d-2fc86442fba9
    PAGES_USER: html-pages
    PAGES_PASSWORD: 1904
  matrix:
    - nodejs_version: "6"
    - nodejs_version: "8"
    - nodejs_version: "9"
    - nodejs_version: "10"

# build platform, i.e. x86, x64, Any CPU. This setting is optional.
platform:
  - x86
  - x64

# branches to build
branches:
  # whitelist
  only:
    - master

# Install scripts. (runs after repo cloning)
install:
  # Get the latest stable version of Node.js or io.js
  - ps: Install-Product node $env:nodejs_version $env:platform
  # install modules
  - npm install

# Post-install test scripts.
test_script:
  - set PATH=node_modules\.bin;%APPDATA%\npm;%PATH%
  # Output useful info for debugging.
  - node --version
  - npm --version
  # run tests
  - npm test

# Don't actually build.
build: off
